# 10 連立一次方程式の解法（ガウスの消去法）

線形方程式の典型例である連立一次方程式 **$Ax=b$** の解を求めるためには **ガウスの消去法** という非常に優れた解法があります。ここではガウスの消去法のアルゴリズムをプログラムとして実装する方法を考えてみましょう。

## 10.1 （単純な）ガウスの消去法

それではガウスの消去法を復習しながらプログラムを作成していきます。以下の3元連立一次方程式について考えます。

$$
\begin{cases} 3x_1 + x_2 + x_3 &= 13 \\ 
5x_1 + x_2 + 3x_3 &= 20 \\
4x_1 + 2x_2 + x_3 &= 13
\end{cases}
$$


行列形式で表すと次のようになります．

$$
\begin{bmatrix}
3 & 1 & 2 \\
5 & 1 & 3 \\
4 & 2 & 1 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
13 \\
20 \\
13 \\ 
\end{bmatrix}
$$

それでは、次の手順（ガウスの消去法）でこの連立方程式を解いてみます。

1. **第1列の2行目と3行目を0にする．**
具体的には「第1行$ \times(-\frac{5}{3}) + 第2行 $」，「第1行 $\times (-\frac{4}{3}) + 第3行 $」とします．

$$
\begin{bmatrix}
3 & 1 & 2 \\
0 & -\frac{2}{3} & -\frac{1}{3} \\
0 & \frac{2}{3} & -\frac{5}{3} \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
13 \\
-\frac{5}{3} \\
-\frac{13}{3} \\ 
\end{bmatrix} \hspace{3cm}(6.2)
$$

2. **第2列の3行目を0とする**
具体的には(6.2)式において、「第2行 $\times$ 1 + 第3行」とします。

$$
\begin{bmatrix}
3 & 1 & 2 \\
0 & -\frac{2}{3} & -\frac{1}{3} \\
0 & 0 & -2 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
13 \\
-\frac{5}{3} \\
-6 \\ 
\end{bmatrix} \hspace{3cm}(6.2)
$$

ここまでの手順が**前進消去**と呼ばれる操作になります。
3. $x_3, x_2, x_1$ の順に後ろから代入して解を求めます。

$$
%%\begin{array}
%\begin{cases}
x_3 = \frac{-6}{-2} = 3 \\
x_2 = -\frac{3}{2}(-\frac{5}{3}+\frac{1}{3} \times 3) =1 \\ 
x_1 = \frac{1}{3}(13-1-2 \times 3)=2
%\end{cases}
%%\end{array}
$$

この手順が**後退代入**と呼ばれる操作になります。

それでは上記の手順（アルゴリズム）に基づいてプログラムを作成していきましょう。次のプログラムは上記1の手順、つまり**「行の基本変形を用いて2行目以降の1列目の成分を0とするプログラム」**になります。

In [1]:
import numpy as np

# 解きたい連立方程式を準備
mat01=np.array([[3.0, 1.0, 2.0],
                [5.0, 1.0, 3.0], 
                [4.0, 2.0, 1.0]])
vect01=np.array([13.0, 20.0, 13.0])
N = mat01.shape[0]

# 前進消去1 - 2行目の1列目を消去
i = 1
alpha = -mat01[i][0] / mat01[0][0]
for j in range(N):
    mat01[i][j] = mat01[i][j] + alpha * mat01[0][j]
vect01[i] = vect01[i] + alpha * vect01[0]

# 前進消去1 - 3行目の1列目を消去
i = 2
alpha = -mat01[i][0] / mat01[0][0]
for j in range(N):
    mat01[i][j] = mat01[i][j] + alpha * mat01[0][j]
vect01[i] = vect01[i] + alpha * vect01[0]

# 1列目の成分が0になっているか確認
print(mat01, "\n",vect01)

[[ 3.          1.          2.        ]
 [ 0.         -0.66666667 -0.33333333]
 [ 0.          0.66666667 -1.66666667]] 
 [13.         -1.66666667 -4.33333333]


行ごとに1列目成分を0とする計算部分を`for`ループを用い表現します。

In [2]:
import numpy as np

mat01=np.array([[3.0, 1.0, 2.0],[5.0,1.0,3],[4.0,2.0,1.0]])
vect01=np.array([13.0, 20.0, 13.0])
N=mat01.shape[0] #正方行列の次元

for i in range(0+1, N):
    '''行の基本変形を用いて2行目以降の1列目の成分を0とするプログラム'''
    alpha=-mat01[i][0] / mat01[0][0]
    for j in range(0, N):
        mat01[i][j]=mat01[i][j] + alpha * mat01[0][j]
    vect01[i] = vect01[i] + alpha * vect01[0]     

print(mat01, "\n", vect01)

[[ 3.          1.          2.        ]
 [ 0.         -0.66666667 -0.33333333]
 [ 0.          0.66666667 -1.66666667]] 
 [13.         -1.66666667 -4.33333333]


プログラムの説明の前に，**「行の基本変形のアルゴリズム部分」**と**「それを使う部分」**を分けて見通しをよくするために、「行の基本変形を行う部分」を関数化します。

In [3]:
import numpy as np

def trans_mat1(mat01, vect01, N):
    '''行の基本変形を用いて2行目以降の一列目の成分を0とする関数'''
    for i in range(1, N):
        alpha=-mat01[i][0] / mat01[0][0]
        for j in range(0, N):
            mat01[i][j]=mat01[i][j] + alpha * mat01[0][j]
        
    return mat01

if __name__=='__main__':
    mat01=np.array([[3.0, 1.0, 2.0],[5.0,1.0,3],[4.0,2.0,1.0]])
    vect01=np.array([13.0, 20.0, 13.0])
    N=mat01.shape[0]

    print(trans_mat1(mat01, vect01, N))

[[ 3.          1.          2.        ]
 [ 0.         -0.66666667 -0.33333333]
 [ 0.          0.66666667 -1.66666667]]


関数`def trans_mat():`の中身が「行の基本変形を用いて2行目以降の1列目の成分を $0$にするアルゴリズム部分」になります。 2重の`for`ループを使用しており1つ目のループは「2行目以降の1列目の成分を $0$ にするように1行目を2行目以降へ順番に加えるループ」を表しており2つ目のループは「列成分を計算するループ」を表しています。1行目を用いて2行目以降の1列目の成分を 0 とするため1つ目のループの開始条件は$1$からとなってます。`alpha`は消去作業を行う際に一時的に利用する変数です。

続いて、「3行目の2列目の成分を$0$にするアルゴリズム」について考えます。

In [4]:
import numpy as np

# 解きたい連立方程式を準備
mat01=np.array([[3.0, 1.0, 2.0],
                [5.0, 1.0, 3.0], 
                [4.0, 2.0, 1.0]])
vect01=np.array([13.0, 20.0, 13.0])
N = mat01.shape[0]

# 前進消去1 - 2行目の1列目を消去
i = 1
alpha = -mat01[i][0] / mat01[0][0]
for j in range(N):
    mat01[i][j] = mat01[i][j] + alpha * mat01[0][j]
vect01[i] = vect01[i] + alpha * vect01[0]

# 前進消去1 - 3行目の1列目を消去
i = 2
alpha = -mat01[i][0] / mat01[0][0]
for j in range(N):
    mat01[i][j] = mat01[i][j] + alpha * mat01[0][j]
vect01[i] = vect01[i] + alpha * vect01[0]

# 前進消去2 - 3行目の2列目を消去
i = 2
beta = -mat01[i][1] / mat01[1][1]
for j in range(1, N):
    mat01[i][j] = mat01[i][j] + beta * mat01[1][j]
vect01[i] = vect01[i] + beta * vect01[1]

# 上三角行列ができているか確認
print(mat01)

[[ 3.          1.          2.        ]
 [ 0.         -0.66666667 -0.33333333]
 [ 0.          0.         -2.        ]]


## 問題1
上のプログラムをカウンター変数`i`について、`for`ループを使ったプログラムを作りなさい

In [5]:
#解答 問題1
import numpy as np

# 解きたい連立方程式を準備
mat01=np.array([[3.0, 1.0, 2.0],
                [5.0, 1.0, 3.0], 
                [4.0, 2.0, 1.0]])
vect01=np.array([13.0, 20.0, 13.0])
N = mat01.shape[0]

# 前進消去 - 2,3行目の1列目を消去, 3行目の2列目を消去
for k in range(0, N-1):
    for i in range(k+1, N):
        alpha = -mat01[i][k] / mat01[k][k]
        for j in range(k, N):
            mat01[i][j] = mat01[i][j] + alpha * mat01[k][j]
        vect01[i] = vect01[i] + alpha * vect01[k]

print(mat01)

[[ 3.          1.          2.        ]
 [ 0.         -0.66666667 -0.33333333]
 [ 0.          0.         -2.        ]]


## 問題2
問題1のプログラムを関数化しなさい．

In [6]:
# 解答　問題2
import numpy as np

# 基本変形をまとめて関数にする
def gauss_elimination(mat, vect, N):
    # 上三角行列を作る
    for k in range(0, N-1):
        for i in range(k+1, N):
            alpha = -mat[i][k] / mat[k][k]
            for j in range(k, N):
                mat[i][j] = mat[i][j] + alpha * mat[k][j]
            vect[i] = vect[i] + alpha * vect[k]
            
    return mat

if __name__=='__main__':
    mat01=np.array([[3.0, 1.0, 2.0],[5.0,1.0,3],[4.0,2.0,1.0]])
    vect01=np.array([13.0, 20.0, 13.0])
    N=mat01.shape[0]

    print(gauss_elimination(mat01, vect01, N))

[[ 3.          1.          2.        ]
 [ 0.         -0.66666667 -0.33333333]
 [ 0.          0.         -2.        ]]


## 問題3
後退代入を加えガウスの消去法のプログラムを作成しなさい。 （ヒントは下記）

    import numpy as np

    def gauss_elimination(mat01, vect01, N):

        """前進消去により行列を上三角行列へ基本変形"""
        for k in range(0, N-1):
            for i in range(k+1, N):
                alpha=-mat01[i][k] / mat01[k][k]
                for j in range(k, N):
                    mat01[i][j]=mat01[i][j] + alpha * mat01[k][j]
                vect01[i]=vect01[i]+alpha*vect01[k]

        """後退代入により下の行から順に代入し解を求める。(forループを2回用い下記の計算を行えばよい)"""
    
$$
vect01[k]=\frac{vect01[k]-\sum^{N-1}_{j=k+1}mat01[k][j]vect01[j]}{mat01[k][k]}
$$

    if name=='main':

        """メイン関数　係数行列・定数項・行列サイズを用意 Ax=b"""
        mat01=np.array([[3.0, 1.0, 2.0],[5.0,1.0,3],[4.0,2.0,1.0]])
        vect01=np.array([13.0, 20.0, 13.0])
        N=mat01.shape[0]

        gauss_elimination(mat01, vect01, N)
        print(vect01)

解[2,1,3]

In [7]:
# 解答　問題3
import numpy as np

# 基本変形をまとめて関数にする
def gauss_elimination(mat, vect, N):
    # 上三角行列を作る
    for k in range(0, N-1):
        for i in range(k+1, N):
            alpha = -mat[i][k] / mat[k][k]
            for j in range(k, N):
                mat[i][j] = mat[i][j] + alpha * mat[k][j]
            vect[i] = vect[i] + alpha * vect[k]
    # 後退代入
    #for k in range(N):
    for i in reversed(range(N)):
        #i = (N-1) - k
        vect[i] = vect[i] / mat01[i][i]
        for j in range(i+1, N):
            vect[i] -= mat01[i][j]*vect[j] / mat01[i][i]
            
    return vect

if __name__=='__main__':
    mat01=np.array([[3.0, 1.0, 2.0],[5.0,1.0,3],[4.0,2.0,1.0]])
    vect01=np.array([13.0, 20.0, 13.0])
    N=mat01.shape[0]

    print(gauss_elimination(mat01, vect01, N))


[2. 1. 3.]


## 問題4
次の3元連立一次方程式を上記のプログラムと手計算で解きなさい。現れた結果を見比べながらプログラムを実行した際に何が起こっているのか推測しなさい。

$$
\begin{bmatrix}
2 & 1 & 1 \\
4 & 2 & 5 \\
8 & 8 & 9 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
15 \\
39 \\
83 \\ 
\end{bmatrix}
$$


## 10.2 ピボット選択付きガウスの消去法

16.1のプログラムは行列の対角成分$mat01[k][k]=0$の時には上手く解けません。そこで、行の入れ替えを行いながらガウスの消去法を実行するプログラムへと改良しましょう。<br />
以下の連立一次方程式について考えます。

$$
\begin{bmatrix}
0 & 1 & 2 \\
1 & 0 & 3 \\
3 & 1 & 0 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
2 \\
2 \\
-3 \\ 
\end{bmatrix}
$$

1. 上の行列の第1列の絶対値最大要素は第3行の$3$なので第1行と第3行を交換します。

$$
\begin{bmatrix}
3 & 1 & 0 \\
1 & 0 & 3 \\
0 & 1 & 2 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
-3 \\
2 \\
2 \\ 
\end{bmatrix}
$$

2. 先ほどのガウスの消去法と同様に第1列の2行目と3行目を$0$にする。

$$
\begin{bmatrix}
3 & 1 & 0 \\
0 & -\frac{1}{3} & 3 \\
0 & 1 & 2 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
-3 \\
3 \\
2 \\ 
\end{bmatrix}
$$

3. 第2列の第2行以下で絶対値が最大のものは第3行の$1$なので、第2行と第3行を入れ替えます。

$$
\begin{bmatrix}
3 & 1 & 0 \\
0 & 1 & 2 \\
0 & -\frac{1}{3} & 3 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
-3 \\
2 \\
3 \\ 
\end{bmatrix}
$$

ここまでの手順で前進消去が終わりです。後は後退代入を行えば解 $x_1,x_2,x_3$ を求めることが出来ます。

これをn次元連立一次方程式について行うには次のような手順を実装すればいいことになります。 ただし、すでに消去作業を$k−1$回行っているとします。

1. $k$回目の消去作業において、 $ \left| a_{ik} \right|　(i=k,k+1,⋯,n)$ のうちで最大のものを調べて、その行番号を$ip$とする。

2. $ip \neq k$ならば、$k$行目と$ip$行目を入れ替えて消去作業を行う。

行列の列方向に要素を調べその最大要素に着目し行の入れ替えを行います。この行列の最大要素のことを**ピボット**といい、この操作が**部分ピボット選択**の勘所になります。アルゴリズムは次のようになります。

部分ピボット選択付きガウスの消去法のアルゴリズム

    for k in range(0, N-1)  
        a_max(aの最大値)として絶対値a_kkを代入　#絶対値関数np.abs()を使うと良い。
        ipへ最大値を持つ行番号kを代入  
        for i in range(k, N)
            if 絶対値a_ik > a_max
                a_maxへ絶対値a_ikを代入
                ipへ最大値を持つ行番号iを代入
        if a_max < epsilon #epsilon=2^{50}程度
            print("mat01は正則ではない")
        if ip != k
            for j=k, k+1,…, N
                a_kjとa_{ip,j}の入れ換え #np.arrayを代入するときにはcopy()メソッドを使用すると良い（例えば2×2行列のarray配列の1行目を変数tmpへコピーするとき、tmp=array[i].copy()）。
            b_kとb_{ip}の入れ換え
        前進消去
    後退代入

$a_{max}=0$の判定を$a_{max}<ϵ$としていることに注意して下さい。浮動小数点演算では必ず丸め誤差が入るのでコンピュータで計算した$a_{max}$が$0$になることはまずありません。したがって十分小さい正数$\epsilon$を用い$a_{max}< \epsilon$とするのが一般的です。

## レポート問題
ピボット選択付きガウスの消去法のプログラムを作成しなさい。
〆切：11/05（日）までにGoogleClassroomでjupyter notebook形式「id_学籍番号_05.ipynb」形式で送ること．

In [1]:
# 解答　レポート問題
import numpy as np

def gauss_elimination2(mat01, vect01, N):
    epsilon=pow(2,-20)
    for k in range(0, N-1):
        amax=abs(mat01[k][k])
        ip=k
        for i in range(k, N):
            if abs(mat01[i][k])>amax:
                amax=abs(mat01[i][k])
                ip=i
        
        if amax < epsilon:
            print("mat01は正則ではない")
        
        if ip !=k:
            tmp=mat01[ip].copy()
            mat01[ip]=mat01[k].copy()
            mat01[k]=tmp.copy()
            
            tmp1=vect01[ip].copy()
            vect01[ip]=vect01[k].copy()
            vect01[k]=tmp1.copy()
        
        for i in range(k+1, N):
            alpha=-mat01[i][k] / mat01[k][k]
            for j in range(k, N):
                mat01[i][j]=mat01[i][j] + alpha * mat01[k][j]
            vect01[i]=vect01[i]+alpha*vect01[k]
        
    temp=0
    for k in range(N-1, -1, -1):
        temp=vect01[k]
        if k !=N-1:
            for j in range(k+1, N):
                temp=temp-mat01[k][j] * vect01[j]
                #print(j, temp)
        vect01[k]=temp/ mat01[k][k]
        #print(vect01)

if __name__=='__main__':
    mat01=np.array([[3.0, 1.0, 2.0],[5.0,1.0,3],[4.0,2.0,1.0]])
    vect01=np.array([13.0, 20.0, 13.0])
    N=mat01.shape[0]

    gauss_elimination2(mat01, vect01, N)
    print(mat01)
    print(vect01)

[[ 5.          1.          3.        ]
 [ 0.          1.2        -1.4       ]
 [ 0.          0.          0.66666667]]
[2. 1. 3.]


## 10.3 scipy.linalgパッケージを用いた連立一次方程式の解法

pythonには`scipy`という科学技術計算ライブラリが用意されており、その中に線形代数パッケージが用意されています．詳細については[ここ](https://docs.scipy.org/doc/scipy/reference/linalg.html)．連立一次方程式の解法には`solve()`関数を用います．

$$
\displaystyle{Ax=b}
$$

$$
\begin{bmatrix}
3 & 1 & 2 \\
5 & 1 & 3 \\
4 & 2 & 1 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
13 \\
20 \\
13 \\ 
\end{bmatrix}
$$

In [9]:
import numpy as np
from scipy import linalg #scipyモジュールからlinalgパッケージをインポート

mat01=np.array([[3.0, 1.0, 2.0],[5.0,1.0,3],[4.0,2.0,1.0]])
vect01=np.array([13.0, 20.0, 13.0])

x=linalg.solve(mat01, vect01) #連立一次方程式
print(x)


[2. 1. 3.]


固有値問題を解く関数も用意されてます．

$$
A= \begin{bmatrix}
1 & -2 \\
3 & 6 \\
\end{bmatrix}
$$

$$
Ax=\lambda x
$$

In [11]:
import numpy as np
import scipy as sp

#mat01=np.array([[3.0, 2.0, -2.0],[1, 2, 0],[1, 1, 1]])
mat02=np.array([[1, -2],[3, 6]])

eig01=sp.linalg.eig(mat02, left=False, right=True) #固有値問題を解く
print(eig01[0]) #固有値を大きい順に出力
print(eig01[1]) #対応する固有ベクトルを出力

[3.+0.j 4.+0.j]
[[-0.70710678  0.5547002 ]
 [ 0.70710678 -0.83205029]]
