# 第0３回 数理工学実験２

## 6 Pythonにおける変数とメモリの深い関係

Numpyについての説明の前にPythonにおける変数がコンピュータ内（メモリ上）でどのように処理されているのか詳しく見ます。

### 6.1 Pythonにおけるデータと変数の取り扱い

In [1]:
a=2
b=a
c=10

Pythonではデータ（値(もちろん、オブジェクトです)）はコンピュータ内では物理的なメモリ上に格納されます。そして、メモリには **（メモリ）アドレス**が割り振られてます（要するにメモリ上の住所のことです）。

Pythonではこのメモリアドレスに対応する識別番号の事を**識別子（identity(id)）** と呼びます（idとメモリアドレ
スは違いますが、同一視しても問題は起きません）。
では早速、変数のidを表示する関数 **`id()`** を使って上の3つの変数のidを表示します。

In [2]:
id(a), id(b), id(c), id(2)

(4308702768, 4308702768, 4308703024, 4308702768)

`a`と`b`のid（`2`のidも）が同じであることが分かるかと思います。実はPythonでは代入操作により**値そのものが代入されるのではなく、値のidが代入されているのです。** この事は`b=a`という操作により`a`の別名として`b`という名前が付いたことを意味してます。`a`も`b`も同じ`2`という値を指しているわけです。一般にオブジェクトの名前やid(アドレス)のことを**参照**と呼ぶことがあります。そして、pythonにおける代入操作`b=a`のことを**参照割り当て**と呼びます。

実はPythonでの変数の定義はC言語やJava言語と大きく異なっています。Pythonでは代入により変数の定義が行われるのに対して、C言語やJava言語では代入なしに定義が行われます。このことが下記のようにPythonとC言語などとの変数の取り扱いの違いを生み出しています。  
(図で説明)

さて、それでは`a`,`c`へ他の値を代入したらどうなるのでしょう。

In [3]:
a=7
c=8
id(a), id(b), id(c)

(4308702928, 4308702768, 4308702960)

In [4]:
a=2
b=2
id(a), id(b)

(4308702768, 4308702768)

`a`,`c`のidが変わったのに対し`b`のidが変わってないことが分かります。つまり、**`a`や`c`は値が変わったというよりむしろ新しく定義しなおされた（再定義）と考えた方が良い**のです。  
Pythonにおける代入操作は参照割り当てであると言いました。このことにより変数の代入操作は注意しなければなりません。下記を見て下さい。

In [5]:
lst01=[0,1,2,3]
lst02=lst01
lst02
id(lst01[1])

4308702736

In [6]:
lst02[1]=100
lst02

[0, 100, 2, 3]

In [7]:
lst01

[0, 100, 2, 3]

In [8]:
id(lst01), id(lst02)

(4354992064, 4354992064)

上記のように`lst02=lst01`と代入操作（参照割り当て）した場合`lst01`と`lst02`は同じリストの別名という事になります。従って`lst02[1]`の値を変更すると同時に`lst01[1]`の値も変更されるわけです。このように同じ実体（変数やリストなどのこと）を示しているか否かを調べる式に**is**演算子があります。

In [9]:
lst01 is lst02

True

### 問題 6.1
次のようにスライシングを用いた代入を行ったリストに代入を行った場合元のリストのデータは変更されるか確認しなさい。

`lst03=[10,20,30,40]
lst04=lst03
lst04[1:3]=[200,300]
lst04,lst03`

さて、少し違った例を見てみます。

In [10]:
lst05=[0,1,2,3]
lst06=lst05
lst06=[0.1, 0.2, 0.3, 0.4] #[0.1, 0.2, 0.3, 0.4]のidを新しくlst06へ代入
lst05, lst06

([0, 1, 2, 3], [0.1, 0.2, 0.3, 0.4])

In [11]:
lst05 is lst06

False

上記のように**インデキシングおよびスライシングではない代入式では新しい変数が再定義されるので、`lst05`と`lst06`は違う実体を表す**ことになります。
続いて、同一のリストを`lst07`,`lst08`へ代入するケースを考えてみます。

In [12]:
lst07=[0,1,2,3]
lst08=[0,1,2,3]
lst07 is lst08

False

上記のように`lst07`, `lst08`の実体は異なっています。このことをidを調べることで具体的に確認してみます。

In [13]:
id(lst07),id(lst08)

(4356917504, 4356996288)

上記のように`lst07`，`lst08`の`id`は異なりオブジェクトとして，別物であることが分かります．では，`lst07`，`lst08`の要素の`id`を調べてみます．

In [14]:
[id(i) for i in lst07],[id(i) for i in lst08]

([4308702704, 4308702736, 4308702768, 4308702800],
 [4308702704, 4308702736, 4308702768, 4308702800])

上記のように`lst07`と`lst08`の要素が持つ値のアドレスは同じものであり，このことは次のようにして調べることもできます。

In [15]:
lst07 == lst08

True

`==`はデータが同じであるか否かを調べ、`is`は実体（ようするにアドレス）が同じであるか否かを示しています。当然ですが、`lst07`のデータを変更しても`lst08`のデータへは影響を与えません。

In [16]:
lst07[1]=10
lst07, lst08

([0, 10, 2, 3], [0, 1, 2, 3])

### 6.2 浅いコピーと深いコピー

　参照割り当てに続いてここでは**浅いコピー**と**深いコピー**について軽く説明します。この段階では参照割り当てと浅いコピーの区別は無いです。ただし、Pythonでは参照割り当て、浅いコピー、深いコピーの3つが明確に区別されますので今後関わってくることを想定して頭の隅に入れといてください。初めに答えを言いますとほとんどのケースでは深いコピーを使うべきです。浅いコピーを使うと予想外の変数までが変更されてしまったりします。どうしてもメモリが足りない場合のみ浅いコピーを用いるべきです（その場合は注意深くコーディングすること！）。  
　浅いコピーと深いコピーの違いが現れるのは複合オブジェクトの場合のみです。複合オブジェクトとはようするにリストの中にリストが入っているケースです。浅いコピーするときには'copy'モジュールの中の**`copy`関数** を深いコピーをするときには**`deepcopy`** 関数を用います。まずは単純なリストの例を示します。この段階では浅いコピーと深いコピーの違いは現れません。

In [17]:
import copy
lst08 = [1,2,3,4]

In [18]:
lst09= copy.copy(lst08)
lst09

[1, 2, 3, 4]

In [20]:
lst09 is lst08

False

In [21]:
lst09[1]=20
lst09, lst08

([1, 20, 3, 4], [1, 2, 3, 4])

上記のように`lst08`と`lst09`の実体は別物であることが分かります．これは`deepcopy()`を用いても同じです。

### 問題 6.2
`deepcopy()`関数を用いて上記と同じ結果になることを確認しなさい。

それでは、浅いコピーと深いコピーの違いが現れる複合オブジェクトの例を見てみましょう。

In [19]:
import copy
lst10=[1,2,[30,40]]
lst10

[1, 2, [30, 40]]

In [20]:
lst11=copy.copy(lst10)
lst11

[1, 2, [30, 40]]

In [21]:
lst11[1]=20
lst10, lst11

([1, 2, [30, 40]], [1, 20, [30, 40]])

In [22]:
lst11[2][0]=300
lst10, lst11

([1, 2, [300, 40]], [1, 20, [300, 40]])

In [23]:
lst10[2] is lst11[2]

True

浅いコピーを行った場合`lst10`の最上位データ`1`,`2`については`lst11`の最上位データとの関係が切れてますが、ネストされている`[30, 40]`については`lst10`と`lst11`の関係は切れてません。したがって、上記のような動作になるわけです。  
同じことを`deepcopy`関数を用いて行います。

In [24]:
import copy
lst12=[1,2,[30,40]]
print(f'lst12={lst12}')
lst13=copy.deepcopy(lst12)
print(f'lst13={lst13}')
lst13[1]=20
print(lst12,lst13)
lst13[2][0]=300
print(lst12, lst13)

lst12=[1, 2, [30, 40]]
lst13=[1, 2, [30, 40]]
[1, 2, [30, 40]] [1, 20, [30, 40]]
[1, 2, [30, 40]] [1, 20, [300, 40]]


上記のように`deepcopy`関数を用いるとネストされたデータについても`lst12`と`lst13`の間で関係が切れており独立して取り扱う事ができます。通常、我々はリストをコピーした際にコピー元リストとコピー先リストは独立したものとして取り扱うケースがほとんどです。したがって、**特別な事情がない限りリストをコピーする際には`deepcopy()`関数を使うようにしてください**。

## 7 NumPy

　Pythonは科学技術計算（数値計算、統計解析、データの可視化など）に強い言語として知られていますが、Pythonの標準ライブラリだけでは計算時間が遅いという致命的な弱点があります。それを補うのが**NumPy**ライブラリです。NumPyの肝は**配列の演算を高速に行うこと**にあります（配列とはリストみたいなものです）。科学技術計算では様々な数理モデルのシミュレーションや大規模データ解析を行う際に配列計算を行います。従って、科学技術計算に関わるPythonのライブラリ群のほとんどはNumPyの上に構築されています。そのようなライブラリを自由に使うためにもNumPyの基本はしっかり押さえておきましょう。ちなみに、NumPyが持つ基本的な関数群は下記のとおりです。

- 配列生成・操作
- 数学関数
- 線形代数
- ランダムサンプリング
- 統計関数
- インデックス関連
- ソート・サーチ・カウント
- 多項式計算
- データ入出力
- 離散フーリエ変換と窓関数

これらすべてを覚える必要はありません。「なんとなくこんなことが出来そうだ」と知っておいて、実際に作るときに詳しく調べればいいのです。

### 7.1 ndarray型（多次元配列型）

まず、NumPyライブラリを使うのは次のようにインポートします。

In [25]:
import numpy as np

`numpy`ライブラリを`np`という名前で読み込むという意味です。別に名前は`np`じゃなくとも良いのですが、`np`と読み込むのが一般的なので従いましょう。

### 7.2 ndarray型の作成法

早速、NumPyの根幹である多次元配列オブジェクト**ndarray**型を紹介します。**`ndarray`はリストと異なり、同じ型の要素しか格納することができません**。NumPyでの最も基本的な配列の作り方は下記です。

In [26]:
ary01=np.array([0,1,2,3])
print(ary01)
print(type(ary01))

[0 1 2 3]
<class 'numpy.ndarray'>


上記のように`array()`関数の引数としてリスト（やタプル）を用いる事で`ndarray`型を作成します。  
多次元配列は下記のようにリストをネストして作成します。

In [27]:
ary02=np.array([[0,1,2],[3,4,5]])# 2行3列のnumpy配列の作成
print(ary02)

[[0 1 2]
 [3 4 5]]


　ここで少し多次元配列を扱う際に`ndarray`型について知っておくべきことを説明します。`ary02`は$2 \times 3$の多次元配列となってます。そして、一番外側の括弧`[]`には2つの要素（`[0,1,2]`と`[3, 4, 5]`）が含まれています。この一番外側の括弧`[]`のことを**第0軸**と呼びます。そして軸が持つ要素数のことを**軸の大きさ**（この場合軸の大きさは2）と呼びます。同様に内側の`[]`のことを第1軸と呼び、軸が持つ要素数のことを軸の大きさ（この場合軸の大きさは3）と呼びます。そして、多次元配列が持つ軸の数のことを多次元配列の**次元**と呼びます（この場合次元は2）。

### 問題 7.1
次の多次元配列の（a）「次元」と（b）「各軸の大きさ」をそれぞれ求めなさい。
 1. `[0,1,2,3,4,5]`
 1. `[[0,1,2,3,4,5]]`
 1. `[[[0],[1]],[[2], [3]],[[4],[5]]]`

一定値の配列を作成することもできます。

In [28]:
ary03=np.zeros((3,2))
print(f'ary03={ary03}')
ary04=np.ones((1,2))
print(f'ary04={ary04}')

ary03=[[0. 0.]
 [0. 0.]
 [0. 0.]]
ary04=[[1. 1.]]


`zeros()`は引数として`(行数，列数)`というタプルを用い行列内の全てのデータは0となります（上記の例では行列要素が0の$3 \times 2$行列）。`ones()`は行列内の全てのデータを1とします。また、`zeros_like()`は引数に多次元配列を与えるとそれと同じ形の全要素0の配列を作成します。一定値の配列を作成する関数としてはその他に`empty()`,`full()`,`ones_like()`, `empty_like()`, `full_like()`などがあります。

### 問題 7.2
多次元配列`[[0,1],[2,3],[4,5]]`を引数として用い`full_like()`関数の使い方を学びなさい。  
（[参考マニュアル](https://docs.scipy.org/doc/numpy/reference/generated/numpy.full_like.html#numpy.full_like)）

等間隔の配列を作成するには`arange()`と`linspace()`の2つの関数があります。`arange()`は引数として`([start,]stop[,step])`を持ちます（上記の例では2つ置きに0以上10未満の配列を作成してます）。`arange()`の引数として浮動小数点を用いる場合には下記のようにstopの数を含む場合があるので注意してください。

In [29]:
ary04=np.arange(0,10,2)
print(ary04)

[0 2 4 6 8]


In [30]:
ary05=np.arange(0.1, 0.4, 0.1)
ary05

array([0.1, 0.2, 0.3, 0.4])

`linspace()`関数の使い方は`linspace(start, stop, num)`とします。startは開始値stopは終了値numは要素の数になります。

In [31]:
ary11=np.linspace(0,1,2)
ary11

array([0., 1.])

In [32]:
ary12=np.linspace(0,1,7)
ary12

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

ランダムな行列を作成したい場合もあります。

In [33]:
np.random.seed(1)
ary06=np.random.rand(5) # [0,1]の一様乱数（1次元配列）
print(ary06)
ary07=np.random.rand(2,3) # [0,1]の一様乱数（2×3行列）
print(ary07)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]
[[0.09233859 0.18626021 0.34556073]
 [0.39676747 0.53881673 0.41919451]]


`ndarray`型がPython標準のリストと異なる点は下記のとおりです。

- C言語の配列のようにメモリの連続領域にデータが保存される
- 基本的にすべて同じ型のデータで構成される
- 各次元ごとの要素数が等しい
- 配列中の全要素（もしくは一部の要素）に対し特定の演算を高速に適用できる



### 7.3 ndarray型の属性（アトリビュート）

`ndaray`型は`int`型、`float`型、`str`型と同じように属性（アトリビュート）とメソッドを持っています。属性とは型独自の変数のことで、メソッドとは型独自の関数のことです。
`ndarray`型は幾つかの属性を持っています。例えば、配列の要素の型は次のように`dtype`属性を使って調べることが出来ます。

In [34]:
ary08=np.zeros((3,4))
ary08.dtype

dtype('float64')

配列を生成するときに型を指定する方法は次の通りです。

In [35]:
ary09=np.zeros((3,4), dtype='int64')
print(ary09)
ary09.dtype

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


dtype('int64')

NumPyはPythonで使われる組み込み型を全て使用することが出来ます。 その他にも多くのデータ型を使えます（全てのデータ型は[ここ](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)に載ってます）。  

また、`ndarray`型はdtypeの他にも多くの属性を持っています。その一部は下記のとおりです（全ての属性は[ここ](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#array-attributes)）。

<table>
        <tr>
        <th>属性</th>
        <th>説明（ary00をndarray型のインスタンスとする）</th>
    　　</tr>
        <tr>
        <td>T</td>
        <td>転置行列（ary00.T）</td>
    　　</tr>
        <tr>
        <td>dtype</td>
        <td>配列のデータタイプ（ary00.dtype）</td>
    　　</tr>
        <tr>
        <td>size</td>
        <td>配列の全要素数（ary00.size）</td>
    　　</tr>
        <tr>
        <td>itemsize</td>
        <td>各要素のバイト数（ary00.itemsize）</td>
    　　</tr>
        <tr>
        <td>ndim</td>
        <td>配列の次元（ary00.ndim）</td>
        </tr>
        <tr>
        <td>shape</td>
        <td>配列の形状を示すタプル（ary00.shape）</td>
    　　</tr>
        <tr>
        <td>strides</td>
        <td>各次元方向に一つ隣の要素に移動するために必要なバイト数をタプルで表示したもの（ary00.strides）</td>
    　　</tr>
        <tr>
        <td>flags</td>
        <td>メモリ上における`ndarray`のデータの格納の仕方についての情報</td>
    　　</tr>
        <tr>
        <td>flat</td>
        <td>`ndarray`を1次元配列に変換するイテレータ</td>
    　　</tr>
        <tr>
        <td>nbytes</td>
        <td>`ndarray`の要素によって占められてるバイト単位におけるメモリ消費量</td>
    　　</tr>
        <tr>
        <td>base</td>
        <td>`ndarray`のベースとなるオブジェクト（どのメモリを参照しているのか）</td>
    　　</tr>
</table>

### 7.4 ndarray型のメソッドおよび関数

`ndarray`型は非常に多くのメソッドも持っています。その上，多くのメソッドは関数としても定義されてます。全ての関数・メソッドについてのマニュアルは[ここ](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.html)にあります。
ここでは幾つかについて紹介します。`resize()`メソッドは多次元配列の形を変更します。`resize((第0軸の大きさ, 第1軸の大きさ，第2軸の大きさ…))`として使います。

In [36]:
ary10=np.arange(0,9)
print(ary10)

[0 1 2 3 4 5 6 7 8]


In [37]:
ary11=np.resize(ary10,(3,3)) # np.resize()関数を使う。
print(ary11)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
ary10.resize((3,3)) # .reseize()メソッドを使う。
print(ary10)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 7.5 ndarrayのインデックスとスライス

`ndarray`型のインデックスとスライスはlist型と同じ

In [39]:
ary13=np.arange(10)
print(ary13)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
ary13[2]

np.int64(2)

In [41]:
ary13[1:4]

array([1, 2, 3])

In [42]:
ary13[0:7:2]

array([0, 2, 4, 6])

多次元配列

In [43]:
np.random.seed(2)
ary14=np.random.randint(1, 10, size=(3,2))
ary14

array([[9, 9],
       [7, 3],
       [9, 8]])

In [44]:
ary14[1][0]

np.int64(7)

In [45]:
ary14[2]

array([9, 8])

In [46]:
ary14[2][:]

array([9, 8])

実はndarrayにはスライシングするための固有の記法がありこの記法の方が要素へのアクセスが速いです。

In [47]:
ary14[2,:]

array([9, 8])

### 問題 7.3
次のスライシングはどのような結果となるか、初めに推測したうえで実行しなさい。  
`ary14[1:, 2:]`

### 7.4 ユニバーサル関数

Numpyは配列処理に関して非常に豊富で便利な機能を持っているライブラリです。その中の一つに、**配列の全要素に対して、要素ごとに特定の関数を作用させて返す機能**があります。これを**ユニバーサル関数**と呼びます。標準で用意されているユニバーサル関数もあれば、ユニバーサル関数を自作することもできます(**frompyfunc()**)。

`frompyfunc(関数, 引数の数, 出力の数)`

In [51]:
nlist01=np.arange(12).reshape(2, 6)
print(nlist01)
nlist02=np.zeros((2,6))

#要素毎に2乗（ループバージョン）
for i in range(2):
    for j in range(6):
        nlist02[i][j]=nlist01[i][j]**2

print(f"ループバージョン:\n{nlist02}")

#要素毎に2乗（ユニバーサル関数（ufunc）バージョン）

new_pow01=np.power(nlist01, 2)
print(f"ユニバーサル関数バージョン：\n{new_pow01}")

#要素毎に2乗（自作関数バージョン）
def ori_pow(a):
    b=a**2        
    return b

if __name__ == "__main__":
    uni_pow=np.frompyfunc(ori_pow, 1, 1) # 
    new_pow02=uni_pow(nlist01)
    print(f"自作ユニバーサル関数バージョン：\n{new_pow02}")


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
ループバージョン:
[[  0.   1.   4.   9.  16.  25.]
 [ 36.  49.  64.  81. 100. 121.]]
ユニバーサル関数バージョン：
[[  0   1   4   9  16  25]
 [ 36  49  64  81 100 121]]
自作ユニバーサル関数バージョン：
[[0 1 4 9 16 25]
 [36 49 64 81 100 121]]


### 7.5 ndarrayによる行列計算

ndarray型の行列計算において`*`,`/`,`+`,`-`,`**`, `%`はすべて要素同士の計算になるから注意。

In [52]:
import numpy as np
mat01=np.array([[1,2],[3,4]])
mat02=np.array([[1,0],[-1,0]])

In [53]:
mat01+mat02

array([[2, 2],
       [2, 4]])

In [54]:
mat01-mat02

array([[0, 2],
       [4, 4]])

In [55]:
mat01*mat02

array([[ 1,  0],
       [-3,  0]])

行列積には`@`を用いる

In [56]:
mat01@ mat02

array([[-1,  0],
       [-1,  0]])

In [57]:
np.linalg.matrix_rank(mat01)

np.int64(2)

### レポート問題
1. numpy配列(ndarray)を引数とする、ユニバーサル関数を作成し出力するプログラムを作成しなさい（他の人と異なる関数を評価する。講義でやった数式だけでなく文字列を処理する自作関数などを高く評価する）。
2. [線形代数の数学関数](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.dual.html#linear-algebra)を参考に線形代数の関数群を使って線形代数に関わる計算を行いなさい。ただし、単純な内積や外積ではなく行列の固有値や線型方程式の解を求めなさい．    

**〆切：10/16（水）までにGoogleClassroomでjupyter notebook形式「id_学籍番号_03.ipynb」形式で送ること**